### ISSUE TITLE
Collecting data for Animal Crossing: New Horizons to adjust the preset.

### ISSUE THREAD

**Issue by juo6442** [juo6442/moothumb#16]
Need to collect data which makes the prediction not working.

Is the data fits to one of the current patterns(wave, n-th periods, falling)? or we need to define a new pattern?

**Comment by juo6442** [comment]
99 42/37 34/30 28/91 87

**Comment by juo6442** [comment]
95 91/88 84/139

**Comment by juo6442** [comment]
93 108/138

**Comment by juo6442** [comment]
101 55/47 43/134 90/149 153/143 79/ /66

**Comment by vikkka** [comment]
102 54/51 47/43 109/88 132/142 140/41    Animal Crossing version 1.1.4 a. It looks like a 4-period model except for that 88 in the middle.

**Comment by dnjstlr555** [comment]
What about reverse engineering them?
I saw someone directly edited turnip price using save editor, retracing or something could helpful to trackdown anything related with turnip price algorithms

![image](https://user-images.githubusercontent.com/21963949/79062674-41161300-7cd7-11ea-834c-79a9d5af0e85.png)
[a post about editing turnip price via save editor](https://gbatemp.net/threads/animal-crossing-new-horizons-reverse-engineering-glitches-bugs-etc-thread.560199/page-86#post-8997044)
[and a report that this is working in latest version](https://gbatemp.net/threads/animal-crossing-new-horizons-reverse-engineering-glitches-bugs-etc-thread.560199/page-104#post-8999334)

**Comment by juo6442** [comment]
@dnjstlr555 Unfortunately, I know few about reversing. Do you have any idea?

**Comment by jimmy0017** [comment]
110 97/93 125/184 464/161 113/70 82/90 92/92

**Comment by juo6442** [comment]
Parameter is modified for above data

**Comment by jimmy0017** [comment]
106 95/91 86/82 77/74 70/66 63/59 56/53

**Comment by jimmy0017** [comment]
90 80/75 71/67 102/127 289/178 98/75 64/44
